= Anthill API 문서

:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 3
:sectlinks:

[[Member-API]]
== Member API

[[Member-중복-조회]]

== Member 닉네임 중복 조회
operation::nick-name-duplicate[snippets='http-request,path-parameters,http-response,response-fields']

== Member 아이디 중복 조회
operation::user-id-non-duplicate[snippets='http-request,path-parameters,http-response,response-fields']

== Member 휴대폰번호 중복 조회
operation::user-phone-number-non-duplicate[snippets='http-request,path-parameters,http-response,response-fields']

== Member 회원 가입
operation::member-join-success[snippets='http-request,request-fields,http-response']

== Member 회원 아이디로 조회
operation::member-get-by-id-success[snippets='http-request,path-parameters,http-response,response-fields']

== Member 회원 로그인
operation::member-login-success[snippets='http-request,http-response,response-headers']

[[Board-API]]
== Board API

== 게시글 작성
operation::board-posting-success[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 게시글 조회
operation::board-get-by-id-success[snippets='request-fields,http-response,response-fields']

== 게시글 수정
operation::board-update-success[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 게시글 삭제
operation::board-delete-success[snippets='http-request,request-headers,request-fields,http-response,response-fields']

== 게시글 페이징 조회
operation::board-paging-success[snippets='http-request,http-response,response-fields']